---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    type: ci-cd
    author: intelliqit
spec:
  containers:
    - name: myjenkins
      image: jekins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 8080
